services:
  - type: web
    name: imageforgery
    env: python
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
      pip install --no-cache-dir -r torch-requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.15
      - key: PIP_VERSION
        value: 22.3.1