services:
  - type: web
    name: imageforgery
    env: python
    buildCommand: |
      python -m pip install --upgrade pip==21.3.1
      pip install --no-cache-dir -r requirements-minimal.txt
      pip install --no-cache-dir -r requirements-torch.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.12
      - key: PYTHONPATH
        value: .